### PR TITLE
for evaluation

### PR DESCRIPTION
**Pull request by arooting33**

### CODE REVIEW

**Comment by syuzyy** [comment]
Hi!
 I've had the opportunity to review your "Mad Libs" code, and here's my feedback:
 I'm truly impressed with your creative approach. 
Your code showcases a user-friendly design and offers strong features that contribute to its effectiveness .The modular approach enhances the code's maintainability.
Your attention to detail and focus on user experience are evident in every aspect of your work.
Keep up the excellent work!

**Review by NikolayTyugaev — APPROVED** [review]
Hi! You did a good work (craps game)!
- programm works correctly,
- you've met all requirement,
- the logic is clear (despite of absence of comments)
- division into blocks is clear
- names are clear and correctly styled.
Good work, good luck!

**Comment by backsum** [comment]
Arootin hi!

- The code works as intended, although it is a bit verbose. It is also self-documenting, which is a positive. 
- The logic is very straightforward, and I appreciate that.
- The naming is good but sometimes inconsistent, such as with 'sum' and 'sum3.' 
- It would be nice to merge functions that perform only one task with more versatile functions. All in all, good job!

Btw, it would be better to avoid using sum as a variable name, since it's also the name of a built-in function.

**Review by backsum — APPROVED** [review]

**Comment by arooting33** [comment]
> Arootin hi!
> 
> * The code works as intended, although it is a bit verbose. It is also self-documenting, which is a positive.
> * The logic is very straightforward, and I appreciate that.
> * The naming is good but sometimes inconsistent, such as with 'sum' and 'sum3.'
> * It would be nice to merge functions that perform only one task with more versatile functions. All in all, good job!
> 
> Btw, it would be better to avoid using sum as a variable name, since it's also the name of a built-in function.

thank you for the detailed analysis, true I could have cleaned up the naming of my variables

**Pull request merged**
